to: revealjs
incremental: true

template: /code/template.html 
slide-level: 3

metadata:
  chalkboard: true
  highlightjs: true
  slideNumber: true
  controls: true
  width: "'100%'"
  height: "'100%'"
  theme: simple 
  author:
    - Diego Kiedanski

filters:
  - pantable

html-math-method:
  method: mathjax

