to: revealjs
incremental: true

template: /code/template.revealjs
slide-level: 3

# variables:
  # revealjs-url: "https://cdn.jsdelivr.net/reveal.js/3.0.0"

metadata:
  reveal_plugins: ["notes", "search", "chalkboard"]
  slideNumber: true
  controls: true
  width: "'100%'"
  height: "'100%'"
  theme: simple 
  author:
    - Diego Kiedanski

filters:
- pantable
#
html-math-method:
  method: mathjax

css:
  - /code/style.css

